services:
  trading-postgresql:
    image: postgres:latest
    container_name: trading-postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: trading
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - trading-network
    restart: unless-stopped
  trading-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-scraper
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=trading-postgresql
      - POSTGRES_PORT=5432
    depends_on:
      - trading-postgresql
    networks:
      - trading-network
    volumes:
      - ./app:/app
    restart: unless-stopped

volumes:
    postgresql:
        driver: local
    app:
        driver: local
networks:
    trading-network:
        driver: bridge