FROM apache/airflow:2.10.0-python3.12

ARG AIRFLOW_USER_HOME=/opt/airflow

ADD requirements.txt .
ADD .env .

RUN pip install --upgrade pip && pip install -r requirements.txt

USER root
RUN echo 'airflow ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN playwright install --with-deps
RUN playwright install chromium
RUN sudo pip install playwright-stealth
RUN sudo pip install playwright-recaptcha
RUN sudo apt install ffmpeg -y

USER airflow

#
#RUN apt update -y && apt install -y patch patchutils
#
#RUN set -ex; \
#    cd /home/airflow/.local/lib/python3.12/site-packages/airflow; \
#    curl https://patch-diff.githubusercontent.com/raw/apache/airflow/pull/49721.patch \
#    | filterdiff -p1 -i 'airflow-core/src/airflow/*' | patch -p4 -u --verbose; \
#    curl https://patch-diff.githubusercontent.com/raw/apache/airflow/pull/49581.patch \
#    | filterdiff -p1 -i 'providers/fab/src/airflow/*' | patch -p5 -u --verbose
#
