services:
  trading-postgresql:
    image: postgres:latest
    container_name: trading-postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: trading
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - trading-network
    restart: unless-stopped

volumes:
    postgresql:
        driver: local
networks:
    trading-network:
        driver: bridge